docker-compose.yaml
Add traefik fix so it can redirect only services we wants
=> build: traefik now only loads specified services

api/plugs/src/services/public.controller.ts, api/plugs/src/services/services/services.service.ts, docker-compose.yaml
Added this route according to subject requirements
This has been manually tested
=> Feature: added about.json route

api/twitter/package.json, api/twitter/src/controllers/app.controller.ts, api/twitter/src/controllers/listener.controller.ts, api/twitter/src/dto/Oauth2Start.dto.ts, api/twitter/src/main.ts, api/twitter/src/schemas/twitterAuth.entity.ts, api/twitter/src/services/twitter.service.ts, api/twitter/src/services/twitterAuth.service.ts, api/twitter/yarn.lock
Changed oauth2 response code from redirect to url in boddy with 200 code
=> Fix: Changed oauth2 response 

mobile/Dockerfile, mobile/android/settings.gradle, mobile/lib/ui-toolkit/cards/EventSelection.dart, mobile/lib/ui-toolkit/cards/FieldsEditor.dart
Fixed compilation issues with minor fixes
=> Fix: mobile build

api/user/src/app.controller.ts, api/user/src/app.module.ts, api/user/src/auth/auth.module.ts, api/user/src/auth/jwt.strategy.ts, api/user/src/main.ts, api/user/src/public/public.controller.ts, api/user/src/users/crsfToken.entity.ts, api/user/src/users/user.entity.ts, api/user/src/users/users.module.ts, api/user/src/users/users.service.ts
Added a table in database to handle all crsf active tokens an user has.
=> Feature: added multiple sessions support

mobile/lib/main.dart, mobile/lib/pages/settings/Settings.dart, mobile/lib/ui-toolkit/navbar.dart
Added a correct color disconnect button and added a 'Change Theme' option which is save locally in preferences.
=> Feature: added complete settings page

mobile/lib/models/plug/PlugDetails.dart, mobile/lib/pages/navigate/navigate.dart, mobile/lib/pages/plugs/Plugs.dart, mobile/lib/ui-toolkit/cards/ServiceCard.dart, mobile/lib/ui-toolkit/navbar.dart
Added a Navigate page that allows to filter both plugs and services and plugs by their innate data.
=> Feature: added navigate page in mobile app

api/starton/package.json, api/starton/src/app.controller.ts, api/starton/src/app.module.ts, api/starton/src/app.service.ts, api/starton/src/entities/webhook.entity.ts, api/starton/src/main.ts, api/starton/src/public/public.controller.ts, api/starton/src/services/amqp.service.ts, api/starton/src/services/starton.service.ts, api/starton/src/services/webhook.service.ts, api/starton/yarn.lock
Add the ability to have multiples webhooks for a single user through uuid
=> feat(api): starton webhook id

api/plugs/src/events-connector/services/variables.service.ts, api/plugs/src/plugs/plugs.service.ts, api/plugs/src/plugs/public.controller.ts, api/user/src/public/public.controller.ts
Added the possibility to use variable as part of field value instead of being the whole value
=> Feature: better variables management

web/src/components/AccountTile.tsx, web/src/components/Header.tsx, web/src/utils/api.ts
When the user click on the acount tile component, he get disconnected and redirected to the login page
Click has now logout effect
=> Feature: logout on account tile click

api/user/src/public/public.controller.ts, docker-compose.yaml
Added an endpoint to retrieve user informations to display them on frontend
=> Feature: added /me endpoint on user microservice

web/src/components/AccountTile.tsx, web/src/components/Header.tsx, web/src/utils/api.ts
Implemented User Infos from API to header card.
=> feat(web/userInfos): implemented User Infos from API to Header card

api/plugs/Dockerfile, api/plugs/src/app.controller.ts, api/plugs/src/app.module.ts, docker-compose.yaml
Added a healthcheck test on plugs container to let services containers start only when plugs is up
=> Build: added healthy dependencies on plugs microservice

web/src/components/TriggerCard.tsx, web/src/pages/PlugCreatePage.tsx
Added a button between each event/actions to create plug page. Also added a delete icon on each action to remove them from the plug.
=> Feature: add and delete buttons for create/edit plug page

web/src/components/PlugCard.tsx, web/src/pages/PlugsPage.tsx, web/src/utils/api.ts
The plug page now contains 2 more buttons, edit (todo) and delete.
=> Feature: added plug delete on plugs page

api/plugs/src/plugs/public.controller.ts, web/src/app/Router.tsx, web/src/components/InputBar.tsx, web/src/components/PlugCard.tsx, web/src/components/TriggerCard.tsx, web/src/pages/PlugEditPage.tsx, web/src/pages/PlugsPage.tsx, web/src/utils/api.ts
Added a brand new page:tm: that allow to edit any plugs:copyright: by clicking on edit in the plugs page.
The user will be able to change any field availaible or delete the plug.
=> Feature: plug edition page (edit and remove)

api/plugs/src/events-connector/events-connector.controller.ts, api/plugs/src/plugs/public.controller.ts, api/starton/src/app.controller.ts, api/starton/src/app.module.ts, api/starton/src/config/starton.ts, api/starton/src/entities/webhook.entity.ts, api/starton/src/public/public.controller.ts, api/starton/src/services/amqp.service.ts, api/starton/src/services/starton.service.ts, api/starton/src/services/webhook.service.ts
This PR implements the latests breaking changes such as plugId and eventId.
It also adds a lot more events for starton microservice
webhook entity for starton microservice
=> Feat(api): add more events into starton + implements the latest breaking changes

mobile/android/app/build.gradle, mobile/android/app/src/main/AndroidManifest.xml, mobile/lib/PlugApi.dart, mobile/lib/pages/home/Home.dart, mobile/lib/pages/home/HomeCard.dart, mobile/lib/pages/navigate/navigate.dart, mobile/lib/ui-toolkit/PlugItStyle.dart, mobile/lib/ui-toolkit/navbar.dart, mobile/macos/Flutter/GeneratedPluginRegistrant.swift, mobile/pubspec.lock, mobile/pubspec.yaml, mobile/windows/flutter/generated_plugin_registrant.cc
- Fixed UI failure not displaying home page + added some cards
- Fixed OAuth2 with services and redirection
- Fixed filter in navigate page + added an option to filter by types
=> Fix: Home page UI / Services OAuth2 / Filter in Navigate

mobile/android/app/build.gradle, mobile/lib/PlugApi.dart, mobile/lib/pages/auth/Login.dart, mobile/lib/ui-toolkit/buttons/GoogleAuthButton.dart, mobile/pubspec.lock, mobile/pubspec.yaml
=> Feature: Mobile google sso

api/user/package.json, api/user/src/public/public.controller.ts, api/user/src/sso/dto/ssoLogin.dto.ts, api/user/src/sso/google/googleSso.service.ts, api/user/src/sso/sso.service.ts, api/user/yarn.lock
Update sso login endpoint on user microservice to support mobile sso workflow
=> Feature: mobile sso endpoint update

mobile/lib/models/plug/PlugDetails.dart, mobile/lib/pages/auth/Login.dart, mobile/lib/pages/plugs/Plugs.dart, mobile/lib/pages/plugs/plug_edit_page.dart, mobile/lib/ui-toolkit/PlugItStyle.dart, mobile/lib/ui-toolkit/bottom-sheets/event_selector.dart, mobile/lib/ui-toolkit/bottom-sheets/service_selector.dart, mobile/lib/ui-toolkit/bottom-sheets/variable_menu.dart, mobile/lib/ui-toolkit/cards/ActionEditCard.dart, mobile/lib/ui-toolkit/cards/CardTitle.dart, mobile/lib/ui-toolkit/cards/ErrorLabel.dart, mobile/lib/ui-toolkit/cards/EventSelection.dart, mobile/lib/ui-toolkit/cards/FieldsEditor.dart, mobile/lib/ui-toolkit/cards/variable_menu.dart, mobile/lib/ui-toolkit/input/InputField.dart, mobile/lib/ui-toolkit/input/string_input.dart, mobile/pubspec.lock, mobile/pubspec.yaml
(Menu Selector == Bottom Sheet Modal)
Refactored plug Edit/Create page:
- removed indexes logics
- added Variable Menu Selector in fields
- added Service/Event Menu Selector
- added Add and Remove Action correctly based on action relative prosition in model
=> Feature: Improved Plug Edit/Create page

web/src/components/FieldEditor.tsx, web/src/components/StepInfo.type.ts, web/src/components/TriggerCard.tsx, web/src/pages/PlugCreatePage.tsx, web/src/pages/PlugEditPage.tsx, web/src/utils/api.ts
Fixed a few bugs that were really annoying during testing phase
=> Fix: minor bugs on web

mobile/lib/models/field/Field.dart, mobile/lib/models/field/Field.g.dart, mobile/lib/pages/plugs/plug_edit_page.dart, mobile/lib/ui-toolkit/bottom-sheets/event_selector.dart, mobile/lib/ui-toolkit/bottom-sheets/service_selector.dart, mobile/lib/ui-toolkit/cards/ActionEditCard.dart, mobile/lib/ui-toolkit/cards/CardTitle.dart, mobile/lib/ui-toolkit/cards/EventSelection.dart, mobile/lib/ui-toolkit/input/string_input.dart
Polished ui and added somme more data
=> Feature: Polished Mobile UI

mobile/lib/models/service/Service.dart, mobile/lib/models/service/Service.g.dart, mobile/lib/pages/plugs/plug_edit_page.dart, mobile/lib/ui-toolkit/PlugItStyle.dart, mobile/lib/ui-toolkit/bottom-sheets/service_selector.dart, mobile/lib/ui-toolkit/bottom-sheets/variable_menu.dart, mobile/lib/ui-toolkit/cards/PlugCard.dart, mobile/lib/ui-toolkit/cards/ServiceCard.dart
Added the color field in the Service model and used it in Service card as bg color. (/!\ READ BREAKING CHANGE)
/!\ Need to test with a version of the Api that provides the required field !, otherwise don't approve/merge !!!
/!\ Need to test with a version of the Api that provides the required field !, otherwise don't approve/merge !!!
=> Feature: added color in Service model and ServiceCard

api/drive/.env.example, api/drive/src/app.module.ts, api/drive/src/config/drive.config.ts, api/drive/src/config/github.config.ts, api/drive/src/controllers/app.controller.ts, api/drive/src/controllers/listen.controller.ts, api/drive/src/dto/ActionFinished.dto.ts, api/drive/src/dto/ActionTrigger.dto.ts, api/drive/src/dto/EventFired.dto.ts, api/drive/src/dto/EventInitialize.dto.ts, api/drive/src/dto/Field.dto.ts, api/drive/src/dto/PlugDisabled.dto.ts, api/drive/src/dto/Variable.dto.ts, api/drive/src/main.ts, api/drive/src/schemas/driveChangesWebhook.entity.ts, api/drive/src/schemas/webhook.entity.ts, api/drive/src/services/amqp.service.ts, api/drive/src/services/driveAuth.service.ts, api/drive/src/services/driveChanges.service.ts, api/drive/src/services/fileActions.service.ts, api/drive/src/services/webhook.service.ts, docker-compose.yaml
Added drive service, adding 2 new events, 14 actions.
=> Feature: Drive Service

mobile/lib/main.dart, mobile/lib/pages/auth/Login.dart, mobile/lib/pages/auth/SignUp.dart, mobile/lib/pages/plugs/Plugs.dart, mobile/lib/pages/plugs/plug_edit_page.dart, mobile/lib/ui-toolkit/PlugItStyle.dart, mobile/lib/ui-toolkit/bottom-sheets/event_selector.dart, mobile/lib/ui-toolkit/buttons/GoogleAuthButton.dart, mobile/lib/ui-toolkit/cards/PlugCard.dart, mobile/lib/ui-toolkit/cards/ServiceCard.dart, mobile/lib/ui-toolkit/input/InputField.dart, mobile/lib/ui-toolkit/navbar.dart, mobile/test/widget_test.dart
After unit tested the app, fixed the following problems:
- inputfields initial value
- wrong icon url fetching
- wrong color typography when in light mode
- missing keys for unit testing
- and more ...
=> Feature: Mobile unit tests and fixes

api/plugs/src/plugs/plugs.service.spec.ts, api/plugs/src/plugs/plugs.service.ts
Added unit test for plugs microservice
=> Tests: added test for plugs microservice

.github/workflows/mobile-ci.yaml, mobile/lib/main.dart, mobile/lib/pages/auth/Login.dart, mobile/lib/pages/auth/SignUp.dart, mobile/test/widget_test.dart
Made preferences optionnal and not used while unit testing.
=> Fix: Mobile added unit testing mod

.github/workflows/api-ci.yaml, api/user/src/auth/auth.service.spec.ts, api/user/src/sso/dto/ssoLogin.dto.ts, api/user/src/users/user.entity.ts, api/user/src/users/users.service.spec.ts, api/user/src/users/users.service.ts
Add tests for user microservice
=> Tests: user

mobile/lib/PlugApi.dart, mobile/lib/main.dart, mobile/lib/pages/auth/Login.dart, mobile/lib/pages/auth/SignUp.dart, mobile/lib/pages/auth/Start-up.dart, mobile/lib/pages/settings/Settings.dart, mobile/lib/ui-toolkit/input/InputField.dart, mobile/lib/ui-toolkit/navbar.dart
Added api settings at start up and in application settings.
=> Feature: Api Settings
